Models/Character.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnePiece.Models
{
    //Character class is a POCO(Plain Old CLR Object). 
    //POCOs do not have a behaviour or logic but has some properties that are used to represent states
    public class Character
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnePiece.Models;
using OnePiece.ViewModels;

namespace OnePiece.Controllers
{
    public class CharactersController : Controller
    {
        // GET: Characters
        public ActionResult Random()
        {
            /*var character = new Character {
                Name = "Monkey D. Luffy"
            };*/
            var characters = new List<Character>
            {
                new Character
                {
                    Id = 1,
                    Name = "Straw Hat Pirates"
                },
                new Character
                {
                    Id = 2,
                    Name = "Animal Kingdom Pirates"
                },
                new Character
                {
                    Id = 3,
                    Name = "Arlong Pirates"
                },
                new Character
                {
                    Id = 4,
                    Name = "Bellamy Pirates"
                },
                new Character
                {
                    Id = 5,
                    Name = "Blackbeard Pirates"
                },
                
            };
            return View("Random", characters);
        }

        [Route("characters/group/{groupName}")]
        public ActionResult ByGroupName(string groupName)
        {
            return Content(groupName);
        }
    }
}

/*
3.1 Animal Kingdom Pirates
3.2	Arlong Pirates
3.3	Bellamy Pirates
3.4	Blackbeard Pirates
3.5	Bliking Pirates
3.6	Big Mom Pirates
3.7	Black Cat Pirates
3.8	Buggy's Band of Pirates
3.9	Caribou
3.10	Dracule Mihawk
3.11	Don Quixote Pirates
3.12	Edward Weevil
3.13	Four Emperors
3.14	Foxy pirates
3.15	Krieg Pirates
3.16	Kuja
3.17	Monkey Mountain Allied Force
3.18	New Fishman Pirates
3.19	Red-haired pirates
3.20	Roger Pirates
3.21	Rocks Pirates
3.22	Straw Hat Grand Fleet
3.23	Sun Pirates
3.24	Thriller Bark Pirates
3.25	Whitebeard Pirates
3.26	Worst generation
*/

Views/Characters/Random.cshtml
@model IEnumerable<OnePiece.Models.Character>
@*@model OnePiece.ViewModels.RandomCharacterViewModel*@

@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Characters By Pirate Groups</h2>


@if (!Model.Any())
{
    <p>We don't have any characters yet.</p>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Characters</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var character in Model)
            {
                <tr>
                    <td>@Html.ActionLink(character.Name, "Details", "Characters", new { id = character.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}

    @*
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>

            @foreach (var characters in Model.Character)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Characters.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    *@